name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Run tests
      run: pytest
